basic:
    name: 'https://www.opploans.com batch 6'
    environments:
        production: 'https://www.opploans.com'
        staging: ''
        development: ''
    breakpoints:
        - 640
        - 1024
        - 1200
    pages:
        - /faqs/how-much-can-i-borrow
        - /faqs/how-do-i-change-my-password
        - /faqs/what-is-oppu-and-what-are-the-credit-education-courses
        - /faqs/what-credit-score-do-i-need-to-apply-for-a-loan
        - /faqs/what-are-the-requirements-and-eligibility-to-apply-for-a-loan
        - /faqs/how-do-i-apply-for-a-loan
        - /faqs/i-receive-fixed-income-can-i-apply
        - /faqs/can-i-change-the-loan-amount-in-my-application
        - /faqs/why-was-my-application-denied
        - /faqs/do-you-accept-co-applicants
    monitoring:
        days: {  }
        type: daily
        schedule_time: '05:30 AM'
        schedule_time_zone: Europe/London
        compare_with: last-production
        compare_with_fresh: production
advanced:
    mask: ''
    remove: ''
    isolate: ''
    delay: 15
    scroll: true
    headers:
        - { header: '', value: '' }
    cookies: ''
    custom_js: ''
    custom_css: ''
    mock_content: ''
    performance:
        workers_production: 30
        workers_nonproduction: 10
        workers_production_delay: 0
        workers_nonproduction_delay: 0
    stabilize: true
